/**
 * Copyright (c) Codice Foundation
 *
 * <p>This is free software: you can redistribute it and/or modify it under the terms of the GNU
 * Lesser General Public License as published by the Free Software Foundation, either version 3 of
 * the License, or any later version.
 *
 * <p>This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details. A copy of the GNU Lesser General Public
 * License is distributed along with this program and can be found at
 * <http://www.gnu.org/licenses/lgpl.html>.
 */
package org.codice.proxy.http;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;
import static org.hamcrest.Matchers.notNullValue;
import static org.hamcrest.Matchers.startsWith;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.doNothing;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.camel.CamelContext;
import org.apache.camel.Route;
import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.spi.RouteController;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.mockito.junit.jupiter.MockitoSettings;
import org.mockito.quality.Strictness;

@ExtendWith(MockitoExtension.class)
@MockitoSettings(strictness = Strictness.LENIENT)
class HttpProxyServiceImplTest {

  private static final String TEST_TARGET_URI = "http://example.com/api";
  private static final String TEST_ENDPOINT_NAME = "testEndpoint";
  private static final int TEST_TIMEOUT = 10000;

  @Mock private CamelContext camelContext;

  @Mock private RouteController routeController;

  private Map<String, String> globalOptions;

  private List<Route> routes;

  private HttpProxyServiceImpl proxyService;

  @BeforeEach
  void setUp() throws Exception {
    globalOptions = new HashMap<>();
    routes = new ArrayList<>();

    when(camelContext.getGlobalOptions()).thenReturn(globalOptions);
    when(camelContext.getRoutes()).thenReturn(routes);
    when(camelContext.getRouteController()).thenReturn(routeController);
    doNothing().when(camelContext).addRoutes(any(RouteBuilder.class));
    doNothing().when(camelContext).start();

    proxyService = new HttpProxyServiceImpl(camelContext);
  }

  @Test
  void testConstants() {
    assertThat(HttpProxyServiceImpl.SERVLET_NAME, is("CamelServlet"));
    assertThat(HttpProxyServiceImpl.GENERIC_ENDPOINT_NAME, is("endpoint"));
    assertThat(HttpProxyServiceImpl.HTTP_PROXY_KEY, is("http."));
    assertThat(HttpProxyServiceImpl.HTTPS_PROXY_KEY, is("https."));
    assertThat(HttpProxyServiceImpl.HTTP_PROXY_HOST_KEY, is("proxyHost"));
    assertThat(HttpProxyServiceImpl.HTTP_PROXY_PORT_KEY, is("proxyPort"));
    assertThat(HttpProxyServiceImpl.HTTP_PROXY_AUTH_METHOD_KEY, is("proxyAuthMethod"));
    assertThat(HttpProxyServiceImpl.HTTP_PROXY_AUTH_USERNAME_KEY, is("proxyAuthUsername"));
    assertThat(HttpProxyServiceImpl.HTTP_PROXY_AUTH_PASSWORD_KEY, is("proxyAuthPassword"));
    assertThat(HttpProxyServiceImpl.HTTP_PROXY_AUTH_DOMAIN_KEY, is("proxyAuthDomain"));
    assertThat(HttpProxyServiceImpl.HTTP_PROXY_AUTH_HOST_KEY, is("proxyAuthHost"));
  }

  @Test
  void testConstructorWithCamelContext() {
    assertThat(proxyService, is(notNullValue()));
    verify(camelContext).addComponent(eq("servlet"), any());
  }

  @Test
  void testConstructorWithNullCamelContext() {
    HttpProxyServiceImpl nullContextService = new HttpProxyServiceImpl(null);
    assertThat(nullContextService, is(notNullValue()));
  }

  @Test
  void testConstructorWithEndpointType() throws Exception {
    when(camelContext.removeComponent(anyString())).thenReturn(null);
    HttpProxyServiceImpl customEndpointService = new HttpProxyServiceImpl(camelContext, "jetty");

    assertThat(customEndpointService, is(notNullValue()));
    verify(camelContext).removeComponent("servlet");
  }

  @Test
  void testConstructorWithServletEndpointType() throws Exception {
    HttpProxyServiceImpl servletService = new HttpProxyServiceImpl(camelContext, "servlet");

    assertThat(servletService, is(notNullValue()));
    verify(camelContext, never()).removeComponent("servlet");
  }

  @Test
  void testStartWithAutoGeneratedEndpointName() throws Exception {
    String endpointName = proxyService.start(TEST_TARGET_URI, TEST_TIMEOUT);

    assertThat(endpointName, startsWith(HttpProxyServiceImpl.GENERIC_ENDPOINT_NAME));
    assertThat(endpointName, is("endpoint0"));
    verify(camelContext).addRoutes(any(RouteBuilder.class));
    verify(camelContext).start();
  }

  @Test
  void testStartIncrements() throws Exception {
    String first = proxyService.start(TEST_TARGET_URI, TEST_TIMEOUT);
    String second = proxyService.start(TEST_TARGET_URI, TEST_TIMEOUT);
    String third = proxyService.start(TEST_TARGET_URI, TEST_TIMEOUT);

    assertThat(first, is("endpoint0"));
    assertThat(second, is("endpoint1"));
    assertThat(third, is("endpoint2"));
    verify(camelContext, times(3)).addRoutes(any(RouteBuilder.class));
  }

  @Test
  void testStartWithZeroTimeoutUsesDefault() throws Exception {
    proxyService.start(TEST_TARGET_URI, 0);

    verify(camelContext).addRoutes(any(RouteBuilder.class));
    verify(camelContext).start();
  }

  @Test
  void testStartWithNegativeTimeoutUsesDefault() throws Exception {
    proxyService.start(TEST_TARGET_URI, -100);

    verify(camelContext).addRoutes(any(RouteBuilder.class));
    verify(camelContext).start();
  }

  @Test
  void testStartWithNamedEndpoint() throws Exception {
    String endpointName = proxyService.start(TEST_ENDPOINT_NAME, TEST_TARGET_URI, TEST_TIMEOUT);

    assertThat(endpointName, is(TEST_ENDPOINT_NAME));
    verify(camelContext).addRoutes(any(RouteBuilder.class));
    verify(camelContext).start();
  }

  @Test
  void testStartWithMatchOnPrefix() throws Exception {
    String endpointName =
        proxyService.start(TEST_ENDPOINT_NAME, TEST_TARGET_URI, TEST_TIMEOUT, true, null);

    assertThat(endpointName, is(TEST_ENDPOINT_NAME));
    verify(camelContext).addRoutes(any(RouteBuilder.class));
  }

  @Test
  void testStartWithBean() throws Exception {
    Object bean = new Object();
    String endpointName =
        proxyService.start(TEST_ENDPOINT_NAME, TEST_TARGET_URI, TEST_TIMEOUT, false, bean);

    assertThat(endpointName, is(TEST_ENDPOINT_NAME));
    verify(camelContext).addRoutes(any(RouteBuilder.class));
  }

  @Test
  void testStop() throws Exception {
    proxyService.start(TEST_ENDPOINT_NAME, TEST_TARGET_URI, TEST_TIMEOUT);
    proxyService.stop(TEST_ENDPOINT_NAME);

    verify(routeController).stopRoute(TEST_ENDPOINT_NAME);
    verify(camelContext).removeRoute(TEST_ENDPOINT_NAME);
  }

  @Test
  void testDestroy() throws Exception {
    proxyService.start(TEST_ENDPOINT_NAME, TEST_TARGET_URI, TEST_TIMEOUT);
    proxyService.destroy();

    verify(routeController).stopRoute(TEST_ENDPOINT_NAME);
    verify(camelContext).removeRoute(TEST_ENDPOINT_NAME);
    verify(camelContext).stop();
    verify(camelContext).removeComponent("servlet");
  }

  @Test
  void testDestroyWithMultipleEndpoints() throws Exception {
    proxyService.start("endpoint1", TEST_TARGET_URI, TEST_TIMEOUT);
    proxyService.start("endpoint2", TEST_TARGET_URI, TEST_TIMEOUT);
    proxyService.destroy();

    verify(routeController).stopRoute("endpoint1");
    verify(routeController).stopRoute("endpoint2");
    verify(camelContext).removeRoute("endpoint1");
    verify(camelContext).removeRoute("endpoint2");
    verify(camelContext).stop();
  }

  @Test
  void testDestroyWithNoEndpoints() throws Exception {
    proxyService.destroy();

    verify(routeController, never()).stopRoute(anyString());
    verify(camelContext, never()).removeRoute(anyString());
    verify(camelContext).stop();
    verify(camelContext).removeComponent("servlet");
  }

  @Test
  void testEnableProxySettingsWithHttpProxy() throws Exception {
    String originalHost = System.getProperty("http.proxyHost");
    String originalPort = System.getProperty("http.proxyPort");

    try {
      System.setProperty("http.proxyHost", "proxy.example.com");
      System.setProperty("http.proxyPort", "8080");

      proxyService.start(TEST_ENDPOINT_NAME, TEST_TARGET_URI, TEST_TIMEOUT);

      assertThat(globalOptions.get("http.proxyHost"), is("proxy.example.com"));
      assertThat(globalOptions.get("http.proxyPort"), is("8080"));
    } finally {
      if (originalHost != null) {
        System.setProperty("http.proxyHost", originalHost);
      } else {
        System.clearProperty("http.proxyHost");
      }
      if (originalPort != null) {
        System.setProperty("http.proxyPort", originalPort);
      } else {
        System.clearProperty("http.proxyPort");
      }
    }
  }

  @Test
  void testEnableProxySettingsWithHttpsProxy() throws Exception {
    String originalHost = System.getProperty("https.proxyHost");
    String originalPort = System.getProperty("https.proxyPort");

    try {
      System.setProperty("https.proxyHost", "secure-proxy.example.com");
      System.setProperty("https.proxyPort", "8443");

      proxyService.start(TEST_ENDPOINT_NAME, TEST_TARGET_URI, TEST_TIMEOUT);

      assertThat(globalOptions.get("https.proxyHost"), is("secure-proxy.example.com"));
      assertThat(globalOptions.get("https.proxyPort"), is("8443"));
    } finally {
      if (originalHost != null) {
        System.setProperty("https.proxyHost", originalHost);
      } else {
        System.clearProperty("https.proxyHost");
      }
      if (originalPort != null) {
        System.setProperty("https.proxyPort", originalPort);
      } else {
        System.clearProperty("https.proxyPort");
      }
    }
  }

  @Test
  void testEnableProxySettingsIgnoresBlankValues() throws Exception {
    String originalHost = System.getProperty("http.proxyHost");

    try {
      System.setProperty("http.proxyHost", "   ");

      proxyService.start(TEST_ENDPOINT_NAME, TEST_TARGET_URI, TEST_TIMEOUT);

      assertThat(globalOptions.containsKey("http.proxyHost"), is(false));
    } finally {
      if (originalHost != null) {
        System.setProperty("http.proxyHost", originalHost);
      } else {
        System.clearProperty("http.proxyHost");
      }
    }
  }
}
